// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecochApp.Infrastructure.Data;

#nullable disable

namespace RecochApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260323220102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecochApp.Core.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Contenido", b =>
                {
                    b.Property<int>("IdContenido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContenido"));

                    b.Property<int?>("CategoriaIdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdContenido");

                    b.HasIndex("CategoriaIdCategoria");

                    b.ToTable("Contenidos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.ModoContenido", b =>
                {
                    b.Property<int>("IdModo")
                        .HasColumnType("int");

                    b.Property<int>("IdContenido")
                        .HasColumnType("int");

                    b.Property<int?>("ContenidoIdContenido")
                        .HasColumnType("int");

                    b.Property<int?>("ModoJuegoIdModo")
                        .HasColumnType("int");

                    b.HasKey("IdModo", "IdContenido");

                    b.HasIndex("ContenidoIdContenido");

                    b.HasIndex("ModoJuegoIdModo");

                    b.ToTable("ModosContenidos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.ModoJuego", b =>
                {
                    b.Property<int>("IdModo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdModo"));

                    b.Property<int>("CantidadJugadores")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TiempoMinutos")
                        .HasColumnType("int");

                    b.HasKey("IdModo");

                    b.ToTable("ModosJuego");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Participante", b =>
                {
                    b.Property<int>("IdParticipante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdParticipante"));

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("SalaIdSala")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioIdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdParticipante");

                    b.HasIndex("SalaIdSala");

                    b.HasIndex("UsuarioIdUsuario");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Sala", b =>
                {
                    b.Property<int>("IdSala")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSala"));

                    b.Property<int?>("AnfitrionIdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("IdAnfitrion")
                        .HasColumnType("int");

                    b.HasKey("IdSala");

                    b.HasIndex("AnfitrionIdUsuario");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Salas");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdParticipante")
                        .HasColumnType("int");

                    b.Property<int>("IdSala")
                        .HasColumnType("int");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<int?>("ParticipanteIdParticipante")
                        .HasColumnType("int");

                    b.Property<int?>("SalaIdSala")
                        .HasColumnType("int");

                    b.HasKey("IdTurno");

                    b.HasIndex("ParticipanteIdParticipante");

                    b.HasIndex("SalaIdSala");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Contenido", b =>
                {
                    b.HasOne("RecochApp.Core.Models.Categoria", "Categoria")
                        .WithMany("Contenidos")
                        .HasForeignKey("CategoriaIdCategoria");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("RecochApp.Core.Models.ModoContenido", b =>
                {
                    b.HasOne("RecochApp.Core.Models.Contenido", "Contenido")
                        .WithMany("ModosContenidos")
                        .HasForeignKey("ContenidoIdContenido");

                    b.HasOne("RecochApp.Core.Models.ModoJuego", "ModoJuego")
                        .WithMany("ModosContenidos")
                        .HasForeignKey("ModoJuegoIdModo");

                    b.Navigation("Contenido");

                    b.Navigation("ModoJuego");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Participante", b =>
                {
                    b.HasOne("RecochApp.Core.Models.Sala", "Sala")
                        .WithMany("Participantes")
                        .HasForeignKey("SalaIdSala");

                    b.HasOne("RecochApp.Core.Models.Usuario", "Usuario")
                        .WithMany("Participantes")
                        .HasForeignKey("UsuarioIdUsuario");

                    b.Navigation("Sala");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Sala", b =>
                {
                    b.HasOne("RecochApp.Core.Models.Usuario", "Anfitrion")
                        .WithMany()
                        .HasForeignKey("AnfitrionIdUsuario");

                    b.Navigation("Anfitrion");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Turno", b =>
                {
                    b.HasOne("RecochApp.Core.Models.Participante", "Participante")
                        .WithMany("Turnos")
                        .HasForeignKey("ParticipanteIdParticipante");

                    b.HasOne("RecochApp.Core.Models.Sala", "Sala")
                        .WithMany("Turnos")
                        .HasForeignKey("SalaIdSala");

                    b.Navigation("Participante");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Categoria", b =>
                {
                    b.Navigation("Contenidos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Contenido", b =>
                {
                    b.Navigation("ModosContenidos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.ModoJuego", b =>
                {
                    b.Navigation("ModosContenidos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Participante", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Sala", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("RecochApp.Core.Models.Usuario", b =>
                {
                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
